/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropiedadesIndexRouteImport } from './routes/propiedades.index'
import { Route as PropiedadesIdRouteImport } from './routes/propiedades.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminPropiedadesRouteImport } from './routes/_authenticated/admin.propiedades'
import { Route as AuthenticatedAdminMensajesRouteImport } from './routes/_authenticated/admin.mensajes'
import { Route as AuthenticatedAdminPropiedadesIndexRouteImport } from './routes/_authenticated/admin.propiedades.index'
import { Route as AuthenticatedAdminPropiedadesNuevaRouteImport } from './routes/_authenticated/admin.propiedades.nueva'
import { Route as AuthenticatedAdminPropiedadesIdRouteImport } from './routes/_authenticated/admin.propiedades.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIndexRoute = PropiedadesIndexRouteImport.update({
  id: '/propiedades/',
  path: '/propiedades/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIdRoute = PropiedadesIdRouteImport.update({
  id: '/propiedades/$id',
  path: '/propiedades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPropiedadesRoute =
  AuthenticatedAdminPropiedadesRouteImport.update({
    id: '/propiedades',
    path: '/propiedades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMensajesRoute =
  AuthenticatedAdminMensajesRouteImport.update({
    id: '/mensajes',
    path: '/mensajes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropiedadesIndexRoute =
  AuthenticatedAdminPropiedadesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPropiedadesRoute,
  } as any)
const AuthenticatedAdminPropiedadesNuevaRoute =
  AuthenticatedAdminPropiedadesNuevaRouteImport.update({
    id: '/nueva',
    path: '/nueva',
    getParentRoute: () => AuthenticatedAdminPropiedadesRoute,
  } as any)
const AuthenticatedAdminPropiedadesIdRoute =
  AuthenticatedAdminPropiedadesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPropiedadesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/propiedades/': typeof PropiedadesIndexRoute
  '/admin/mensajes': typeof AuthenticatedAdminMensajesRoute
  '/admin/propiedades': typeof AuthenticatedAdminPropiedadesRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/propiedades/$id': typeof AuthenticatedAdminPropiedadesIdRoute
  '/admin/propiedades/nueva': typeof AuthenticatedAdminPropiedadesNuevaRoute
  '/admin/propiedades/': typeof AuthenticatedAdminPropiedadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/propiedades': typeof PropiedadesIndexRoute
  '/admin/mensajes': typeof AuthenticatedAdminMensajesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/propiedades/$id': typeof AuthenticatedAdminPropiedadesIdRoute
  '/admin/propiedades/nueva': typeof AuthenticatedAdminPropiedadesNuevaRoute
  '/admin/propiedades': typeof AuthenticatedAdminPropiedadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/propiedades/': typeof PropiedadesIndexRoute
  '/_authenticated/admin/mensajes': typeof AuthenticatedAdminMensajesRoute
  '/_authenticated/admin/propiedades': typeof AuthenticatedAdminPropiedadesRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/propiedades/$id': typeof AuthenticatedAdminPropiedadesIdRoute
  '/_authenticated/admin/propiedades/nueva': typeof AuthenticatedAdminPropiedadesNuevaRoute
  '/_authenticated/admin/propiedades/': typeof AuthenticatedAdminPropiedadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacto'
    | '/nosotros'
    | '/sitemap.xml'
    | '/admin'
    | '/propiedades/$id'
    | '/propiedades/'
    | '/admin/mensajes'
    | '/admin/propiedades'
    | '/admin/'
    | '/admin/propiedades/$id'
    | '/admin/propiedades/nueva'
    | '/admin/propiedades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacto'
    | '/nosotros'
    | '/sitemap.xml'
    | '/propiedades/$id'
    | '/propiedades'
    | '/admin/mensajes'
    | '/admin'
    | '/admin/propiedades/$id'
    | '/admin/propiedades/nueva'
    | '/admin/propiedades'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contacto'
    | '/nosotros'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/propiedades/$id'
    | '/propiedades/'
    | '/_authenticated/admin/mensajes'
    | '/_authenticated/admin/propiedades'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/propiedades/$id'
    | '/_authenticated/admin/propiedades/nueva'
    | '/_authenticated/admin/propiedades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactoRoute: typeof ContactoRoute
  NosotrosRoute: typeof NosotrosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PropiedadesIdRoute: typeof PropiedadesIdRoute
  PropiedadesIndexRoute: typeof PropiedadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/': {
      id: '/propiedades/'
      path: '/propiedades'
      fullPath: '/propiedades/'
      preLoaderRoute: typeof PropiedadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/$id': {
      id: '/propiedades/$id'
      path: '/propiedades/$id'
      fullPath: '/propiedades/$id'
      preLoaderRoute: typeof PropiedadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/propiedades': {
      id: '/_authenticated/admin/propiedades'
      path: '/propiedades'
      fullPath: '/admin/propiedades'
      preLoaderRoute: typeof AuthenticatedAdminPropiedadesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mensajes': {
      id: '/_authenticated/admin/mensajes'
      path: '/mensajes'
      fullPath: '/admin/mensajes'
      preLoaderRoute: typeof AuthenticatedAdminMensajesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/propiedades/': {
      id: '/_authenticated/admin/propiedades/'
      path: '/'
      fullPath: '/admin/propiedades/'
      preLoaderRoute: typeof AuthenticatedAdminPropiedadesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPropiedadesRoute
    }
    '/_authenticated/admin/propiedades/nueva': {
      id: '/_authenticated/admin/propiedades/nueva'
      path: '/nueva'
      fullPath: '/admin/propiedades/nueva'
      preLoaderRoute: typeof AuthenticatedAdminPropiedadesNuevaRouteImport
      parentRoute: typeof AuthenticatedAdminPropiedadesRoute
    }
    '/_authenticated/admin/propiedades/$id': {
      id: '/_authenticated/admin/propiedades/$id'
      path: '/$id'
      fullPath: '/admin/propiedades/$id'
      preLoaderRoute: typeof AuthenticatedAdminPropiedadesIdRouteImport
      parentRoute: typeof AuthenticatedAdminPropiedadesRoute
    }
  }
}

interface AuthenticatedAdminPropiedadesRouteChildren {
  AuthenticatedAdminPropiedadesIdRoute: typeof AuthenticatedAdminPropiedadesIdRoute
  AuthenticatedAdminPropiedadesNuevaRoute: typeof AuthenticatedAdminPropiedadesNuevaRoute
  AuthenticatedAdminPropiedadesIndexRoute: typeof AuthenticatedAdminPropiedadesIndexRoute
}

const AuthenticatedAdminPropiedadesRouteChildren: AuthenticatedAdminPropiedadesRouteChildren =
  {
    AuthenticatedAdminPropiedadesIdRoute: AuthenticatedAdminPropiedadesIdRoute,
    AuthenticatedAdminPropiedadesNuevaRoute:
      AuthenticatedAdminPropiedadesNuevaRoute,
    AuthenticatedAdminPropiedadesIndexRoute:
      AuthenticatedAdminPropiedadesIndexRoute,
  }

const AuthenticatedAdminPropiedadesRouteWithChildren =
  AuthenticatedAdminPropiedadesRoute._addFileChildren(
    AuthenticatedAdminPropiedadesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminMensajesRoute: typeof AuthenticatedAdminMensajesRoute
  AuthenticatedAdminPropiedadesRoute: typeof AuthenticatedAdminPropiedadesRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminMensajesRoute: AuthenticatedAdminMensajesRoute,
  AuthenticatedAdminPropiedadesRoute:
    AuthenticatedAdminPropiedadesRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactoRoute: ContactoRoute,
  NosotrosRoute: NosotrosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PropiedadesIdRoute: PropiedadesIdRoute,
  PropiedadesIndexRoute: PropiedadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
